name: Stats Cards
on:
  schedule: [{ cron: "30 * * * *" }]
  workflow_dispatch:
jobs:
  stats-cards-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=xCaptaiN09&langs_count=14&theme=transparent&hide_progress=true&show_icons=true&hide_border=true
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit stats cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add *.svg
          git commit -m "Update stats cards - [Skip GitHub Action]" || exit 0
          git push
